name: "update-fluidstack-catalog-test"
on:
  push:
    branches:
      - fluidstack-catalog
  workflow_dispatch:

jobs:
  update_fluidstack_catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone SkyPilot repo
        uses: actions/checkout@v3
        with:
          repository: fluidstackio/skypilot
          path: sky
          ref: master
      - name: Clone Catalog repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: catalogs
          token: ${{ secrets.GH_TOKEN_PAT }}
          ref: fluidstack-catalog
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd sky
          pip install .

      - name: Run fetch_fluidstack
        run: |
          version=$(python -c 'import sky; print(sky.clouds.service_catalog.constants.CATALOG_SCHEMA_VERSION)')
          mkdir -p catalogs/catalogs/$version
          cd catalogs/catalogs/$version
          ls $GITHUB_WORKSPACE/sky/clouds/service_catalog/data_fetchers/
          python -m  $GITHUB_WORKSPACE/sky/clouds/service_catalog/data_fetchers/fetch_fluidstack.py

      - name: Commit catalog
        run: |
          version=$(python -c 'import sky; print(sky.clouds.service_catalog.constants.CATALOG_SCHEMA_VERSION)')
          cd catalogs
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m"[Bot] Update FluidStack catalog $version (scheduled at $(date))" || { echo "No changes to commit" && exit 0; }
          git fetch origin
          git rebase origin/master
          git push
